
const char* errorMessages[] = {
    "no error",
    "error while loading binary executable `%s`",
    "error while importing binary executable `%s`",
    "no `run` function in binary executable `%s`",
    "unknown opcode 0x%02x",
    "no `%s` function in binary executable `%s`",
    "no `%s` class in binary executable `%s`",
    "empty stack",
    "invalid operand type",
    "error linking native function `%s`",
    "invalid internal 0x%02x",
    "native error : %s",
    "invalid operand",
    "no member called `%s` in class `%s`",
    "instance variable `%s.%s` is not readable",
    "instance variable `%s.%s` is not writeable",
    "instance method `%s.%s` is private",
    "`self` called outside a class method",
    "`super` called outside a class method",
    "`super` called in a base class",
//    "error while loading debug symbols for `%s`",
};
