/*
    StackObject opcodes.
 */
#pragma once

#include "sublage/types.h"

typedef enum {
    OPCODE_NULL = 0x00,
    OPCODE_BOOLEAN = 0x01,
    OPCODE_INT = 0x02,
    OPCODE_FLOAT = 0x03,
    OPCODE_STRING = 0x04,
    OPCODE_ARRAY = 0x05,
    OPCODE_TYPECOUNT = 6,

    OPCODE_INTERNAL = 0x06,
    OPCODE_INTERNALCALL = 0x07,
    OPCODE_EXTERNALCALL = 0x08,
    OPCODE_RETURN = 0x09,
    OPCODE_JUMP = 0x0a,
    OPCODE_JUMPIFNOT = 0x0b,
    OPCODE_JUMPIF = 0x0c,
    OPCODE_NATIVECALL = 0x0d,
    OPCODE_INTERNALCALL_REF = 0x0e,
    OPCODE_EXTERNALCALL_REF = 0x0f,
    OPCODE_NATIVECALL_REF = 0x10,
    OPCODE_PRIVATE = 0x11,
    OPCODE_VAR_SET = 0x12,
    OPCODE_VAR_GET = 0x13,
    OPCODE_VAR_REF = 0x14,
    OPCODE_DATA = 0x15,

    OPCODE_CLASSREF = 0x16,
    OPCODE_IFIELD_SET = 0x17,
    OPCODE_IFIELDCALL = 0x18,
    OPCODE_IFIELDCALL_REF = 0x19,
    OPCODE_INSTANCE = 0x1a,
} Opcode;
