#pragma once

typedef enum {
    VM_NOERROR,
    VM_ERROR_LOADINGBINEXEC,
    VM_ERROR_LOADINGIMPORT,
    VM_ERROR_NORUNFUNCTION,
    VM_ERROR_UNKNOWNOPCODE,
    VM_ERROR_LINKINGEXTERNALFUNCTION,
    VM_ERROR_LINKINGEXTERNALCLASS,
    VM_ERROR_EMPTYSTACK,
    VM_ERROR_INVALIDOPERANDTYPE,
    VM_ERROR_LINKINGNATIVEFUNCTION,
    VM_ERROR_INVALIDINTERNAL,
    VM_ERROR_NATIVE_ERROR,
    VM_ERROR_INVALIDOPERAND,
    VM_ERROR_INVALIDINSTANCEMEMBER,
    VM_ERROR_WRITEONLYIVAR,
    VM_ERROR_READONLYIVAR,
    VM_ERROR_PRIVATEMETHOD,
    VM_ERROR_SELFOUTSIDECLASS,
    VM_ERROR_SUPEROUTSIDECLASS,
    VM_ERROR_SUPERWITHOUTPARENT,
} VmErrorCode;

extern const char* errorMessages[];
